version: "3"
services:
  app:
    container_name: app
    build: ./golang
    volumes:
      - ./golang:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - "nuxt"
    command: sh -c "fresh"

  nuxt:
    container_name: nuxt
    build: ./nuxt
    ports:
      - 3000:3000
    volumes:
      - ./nuxt:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - "db"
    command: sh -c "yarn && yarn dev"

  db:
    container_name: db
    platform: linux/x86_64 # M1 Mac対応のため
    image: mysql:5.7
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: golang-nuxt-app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      TZ: "Asia/Tokyo"
